#
# $Source: f:/miner/source/misc/rcs/makefile $
# $Revision: 1.4 $
# $Author: matt $
# $Date: 1994/11/27 22:27:23 $
#
# Makefile for misc libaray
#

LIBDIR = ..\main

CCFLAGS = /dNETWORK /dRELEASE /dNDEBUG

# What to install
INSTALL_TARGS = misc.lib parsarg.h error.h

# What libs to build
LIBS = misc

# What objs in the lib
MISC_OBJS = parsarg.obj error.obj

# What to clean
CLEAN_TARGS = *.obj *.lib *.err

misc.lib: $(MISC_OBJS)
	wlib misc.lib $(MISC_OBJS)

error.obj: error.c error.h 
	wcc386 $(CCFLAGS) error.c

parsarg.obj: parsarg.c parsarg.h
	wcc386 $(CCFLAGS) parsarg.c

.PHONY: clean
clean:
	@for %f in ($(CLEAN_TARGS)) do erase %f

