#
# $Source: f:/miner/source/div/rcs/makefile $
# $Revision: 1.3 $
# $Author: matt $
# $Date: 1994/11/21 11:34:49 $
#
# Makefile for bios functions
#

LIBDIR = ..\main

CCFLAGS = /dNETWORK /dRELEASE /dNDEBUG

# What to install, and where to install it
INSTALL_TARGS = div0.lib div0.h div0.inc

# What to clean
CLEAN_TARGS = *.obj *.lib *.err

# What libs to make
LIBS = div0

# What object files for the lib
DIV0_OBJS =  div0.obj

div0.lib: $(DIV0_OBJS)
	wlib /q div0.lib $(DIV0_OBJS)

div0.obj: div0.asm
	masm div0.asm

.PHONY: clean
clean:
	@for %f in ($(CLEAN_TARGS)) do erase %f
