#
# $Source: f:/miner/source/3d/rcs/makefile $
# $Revision: 1.9 $
# $Author: matt $
# $Date: 1994/03/15 21:22:47 $
#
# Makefile for 3d library
#

LIBDIR = ..\main

CCFLAGS = /dNETWORK /dRELEASE /dNDEBUG

# What to install
INSTALL_TARGS = 3d.lib 3d.h 3d.inc

CLEAN_TARGS = *.objs *.lib *.err

# What libs to build
LIBS = 3d

# What objs in the lib
3D_OBJS = globvars.obj setup.obj matrix.obj points.obj draw.obj clipper.obj \
	horizon.obj instance.obj rod.obj interp.obj

#rules and targets common to all Miner makefiles

3d.lib: $(3D_OBJS)
	wlib /q 3d.lib $(3D_OBJS)

3dtest.obj: 3dtest.c
	wcc386 $(CCFLAGS) 3dtest.c

clipper.obj: clipper.asm
	masm clipper.asm
draw.obj: draw.asm
	masm draw.asm
globvars.obj: globvars.asm
	masm globvars.asm
horizon.obj: horizon.asm
	masm horizon.asm
instance.obj: instance.asm 
	masm instance.asm

interp.obj: interp.asm
	masm interp.asm
matrix.obj: matrix.asm
	masm matrix.asm

objects.obj: objects.asm
	masm objects.asm

out.obj: out.asm
	masm out.asm

points.obj: points.asm
	masm points.asm

rod.obj: rod.asm
	masm rod.asm

segment.obj: segment.asm
	masm segment.asm

setup.obj: setup.asm
	masm setup.asm

upvecs.obj: upvecs.asm
	masm upvecs.asm

clean:
	erase $(CLEAN_TARGS)
