#
# $Source: f:/miner/source/iff/rcs/makefile $
# $Revision: 1.5 $
# $Author: john $
# $Date: 1994/02/15 12:51:20 $
#
# Makefile for IFF library
#

LIBDIR = ..\main

CCFLAGS = /dNETWORK /dRELEASE /dNDEBUG

# What to install
INSTALL_TARGS = iff.lib iff.h

CLEAN_TARGS = *.obj *.lib *.err

# What libs to build
LIBS = iff

# What objs in the iff lib
IFF_OBJS = iff.obj

iff.lib: $(IFF_OBJS)
	wlib /q iff.lib $(IFF_OBJS)

iff.obj: iff.c
	wcc386 $(CCFLAGS) iff.c

clean:
	erase $(CLEAN_TARGS)
