#
# $Source: f:/miner/source/bios/rcs/makefile $
# $Revision: 1.18 $
# $Author: john $
# $Date: 1995/03/23 18:27:04 $
#
# Makefile for bios functions
#

LIBDIR = ..\main

CCFLAGS = /dNETWORK /dRELEASE /dNDEBUG

# What to install, and where to install it
INSTALL_TARGS = io.lib joy.h key.h mono.h mouse.h timer.h swift.h dpmi.h ipx.h

# What to clean
CLEAN_TARGS = *.obj *.lib *.err

# What libs to make
LIBS = io

# What object files for the lib
IO_OBJS = key.obj joy.obj mouse.obj timer.obj mono.obj joyc.obj dpmi.obj ipx.obj

io.lib: $(IO_OBJS)
	wlib /q io.lib $(IO_OBJS)

dpmi.obj: dpmi.c
	wcc386 $(CCFLAGS) dpmi.c
ipx.obj: ipx.c
	wcc386 $(CCFLAGS) ipx.c
joyc.obj: joyc.c
	wcc386 $(CCFLAGS) joyc.c
joy.obj: joy.asm
	masm joy.asm
key.obj: key.c
	wcc386 $(CCFLAGS) key.c
mono.obj: mono.c
	wcc386 $(CCFLAGS) mono.c
mouse.obj: mouse.c
	wcc386 $(CCFLAGS) mouse.c
timer.obj: timer.asm
	masm timer.asm

clean:
	erase $(CLEAN_TARGS)
