#
# $Source: f:/miner/source/fix/rcs/makefile $
# $Revision: 1.5 $
# $Author: matt $
# $Date: 1994/11/27 23:21:18 $
#
# Makefile for fixed-point library
#

LIBDIR = ..\main

CCFLAGS = /dNETWORK /dRELEASE /dNDEBUG

# What to install, and where to install it
INSTALL_TARGS = fix.lib fix.h fix.inc

# What to clean
CLEAN_TARGS = *.obj *.lib *.err

# What libs to make
LIBS = fix

# What object files for the lib
FIX_OBJS = fix.obj

fix.lib: $(FIX_OBJS)
	wlib /q fix.lib $(FIX_OBJS)

fix.obj: fix.inc fix.asm
	masm fix.asm

.PHONY: clean
clean:
	@for %f in ($(CLEAN_TARGS)) do erase %f
