#
# Master makefile for Miner source
#
# Makes all the executable by visiting subdirs and making there
#

LIBDIR = ..\main

CCFLAGS = /dNETWORK /dRELEASE /dNDEBUG

CLEAN_TARGS = *.obj *.lib *.err

INSTALL_TARGS = cfile.lib cfile.h nocfile.h

LIBS = cfile

CFILE_OBJS = cfile.obj

cfile.lib: $(CFILE_OBJS)
	wlib /q cfile.lib $(CFILE_OBJS)

cfile.obj: cfile.h cfile.c
	wcc386 $(CCFLAGS) cfile.c

.PHONY: clean
clean:
	@for %f in ($(CLEAN_TARGS)) do erase %f
